config/routes.rb
Rails.application.routes.draw do
	root to: 'clients#index'
  resources :employee_hours
  resources :clients
  resources :addresses
  resources :expenses
  resources :funding_infos
  resources :jobs
  resources :users
  resources :vendors

  get '/403.html', to: 'application#denied', as: :denied

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/funding_info.rb
class FundingInfo < ApplicationRecord
  belongs_to :client
end

app/controllers/funding_infos_controller.rb
class FundingInfosController < ApplicationController
  before_action :set_funding_info, only: [:show, :edit, :update, :destroy]

  # GET /funding_infos
  # GET /funding_infos.json
  def index
    @funding_infos = FundingInfo.all
  end

  # GET /funding_infos/1
  # GET /funding_infos/1.json
  def show
  end

  # GET /funding_infos/new
  def new
		respond_to do |format|
			@funding_info = FundingInfo.new
			format.html
			@funding_info = FundingInfo.new(client_id: params[:client_id])
		  format.js	
		end
  end

  # GET /funding_infos/1/edit
  def edit
		respond_to do |format|
			format.html
			format.js
		end
  end

  # POST /funding_infos
  # POST /funding_infos.json
  def create
    @funding_info = FundingInfo.new(funding_info_params)

    respond_to do |format|
      if @funding_info.save
        format.html { redirect_to @funding_info, notice: 'Funding info was successfully created.' }
        format.json { render :show, status: :created, location: @funding_info }
				format.js
      else
        format.html { render :new }
        format.json { render json: @funding_info.errors, status: :unprocessable_entity }
				format.js
      end
    end
  end

  # PATCH/PUT /funding_infos/1
  # PATCH/PUT /funding_infos/1.json
  def update
    respond_to do |format|
      if @funding_info.update(funding_info_params)
        format.html { redirect_to @funding_info, notice: 'Funding info was successfully updated.' }
        format.json { render :show, status: :ok, location: @funding_info }
				format.js
      else
        format.html { render :edit }
        format.json { render json: @funding_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funding_infos/1
  # DELETE /funding_infos/1.json
  def destroy
    @funding_info.destroy
    respond_to do |format|
      format.html { redirect_to funding_infos_url, notice: 'Funding info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funding_info
      @funding_info = FundingInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funding_info_params
      params.require(:funding_info).permit(:fund_code, :department_code, :program_code, :project_code, :account_code, :client_id)
    end
end

app/helpers/funding_infos_helper.rb
module FundingInfosHelper
end

app/views/funding_infos/_form.html.erb
<%= simple_form_for @funding_info, remote: true do |form| %>
  <% if funding_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funding_info.errors.count, "error") %> prohibited this funding_info from being saved:</h2>

      <ul>
      <% funding_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :fund_code, id: :funding_info_fund_code %>
  </div>

  <div class="field">
    <%= form.input :department_code, id: :funding_info_department_code %>
  </div>

  <div class="field">
    <%= form.input :program_code, id: :funding_info_program_code %>
  </div>

  <div class="field">
    <%= form.input :project_code, id: :funding_info_project_code %>
  </div>

  <div class="field">
    <%= form.input :account_code, id: :funding_info_account_code %>
  </div>

  <div class="field">
    <%= form.input :client_id, as: :hidden, id: :funding_info_client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funding_infos/_funding_info.html.erb
<% if funding_info %>
	<div>
		<%= button_to 'Update', edit_funding_info_path(funding_info), method: :get, remote: true %>
		<br/>
		Funding Code: <%= funding_info.fund_code %>
		<br/>
		Account Code: <%= funding_info.account_code %>
		<br/>
		Program Code: <%= funding_info.program_code %>
		<br/>
		Project Code: <%= funding_info.project_code %>
		<br/>
		Department Code: <%= funding_info.department_code %>
	</div>
<% end %>

app/views/funding_infos/create.js.erb
var node = document.createElement('div')
node.id = "funding-info-<%= @funding_info.id %>"
node.innerHTML = "<%= j render partial: 'funding_info', locals: { funding_info: @funding_info } %>"
var funding_node = document.getElementById('funding-info-forms')
funding_node.innerHTML = ""
funding_node.appendChild(node)

app/views/funding_infos/edit.html.erb
<h1>Editing Funding Info</h1>

<%= render 'form', funding_info: @funding_info %>

<%= link_to 'Show', @funding_info %> |
<%= link_to 'Back', funding_infos_path %>

app/views/funding_infos/edit.js.erb
document.getElementById('funding-info-forms').innerHTML = "<%= j render partial: 'form', locals: { funding_info: @funding_info } %>"

app/views/funding_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funding Infos</h1>

<table>
  <thead>
    <tr>
      <th>Fund code</th>
      <th>Department code</th>
      <th>Program code</th>
      <th>Project code</th>
      <th>Account code</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funding_infos.each do |funding_info| %>
      <tr>
        <td><%= funding_info.fund_code %></td>
        <td><%= funding_info.department_code %></td>
        <td><%= funding_info.program_code %></td>
        <td><%= funding_info.project_code %></td>
        <td><%= funding_info.account_code %></td>
        <td><%= funding_info.client_id %></td>
        <td><%= link_to 'Show', funding_info %></td>
        <td><%= link_to 'Edit', edit_funding_info_path(funding_info) %></td>
        <td><%= link_to 'Destroy', funding_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funding Info', new_funding_info_path %>

app/views/funding_infos/new.html.erb
<h1>New Funding Info</h1>

<%= render 'form', funding_info: @funding_info %>

<%= link_to 'Back', funding_infos_path %>

app/views/funding_infos/new.js.erb
document.getElementById('funding-info-forms').innerHTML = '<%= j render partial: "form", locals: { funding_info: @funding_info } %>'

app/views/funding_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fund code:</strong>
  <%= @funding_info.fund_code %>
</p>

<p>
  <strong>Department code:</strong>
  <%= @funding_info.department_code %>
</p>

<p>
  <strong>Program code:</strong>
  <%= @funding_info.program_code %>
</p>

<p>
  <strong>Project code:</strong>
  <%= @funding_info.project_code %>
</p>

<p>
  <strong>Account code:</strong>
  <%= @funding_info.account_code %>
</p>

<p>
  <strong>Client:</strong>
  <%= @funding_info.client_id %>
</p>

<%= link_to 'Edit', edit_funding_info_path(@funding_info) %> |
<%= link_to 'Back', funding_infos_path %>

app/views/funding_infos/update.js.erb
document.getElementById('funding-info-forms').innerHTML = "<%= j render partial: 'funding_info', locals: { funding_info: @funding_info } %>"