config/routes.rb
Rails.application.routes.draw do
	root to: 'clients#index'
  resources :employee_hours
  resources :clients
  resources :addresses
  resources :expenses
  resources :funding_infos
  resources :jobs
  resources :users
  resources :vendors

  get '/403.html', to: 'application#denied', as: :denied

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :jobs, dependent: :nullify
  has_one  :funding_info, dependent: :destroy

  accepts_nested_attributes_for :funding_info

	def name
		return "#{first_name} #{last_name}"
	end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
				@notice = "Client was successfully updated"
				format.js   { render 'update.js.erb' } 
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :organization, :phone, :email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client, remote: true do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :client_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :client_last_name %>
  </div>

  <div class="field">
    <%= form.label :organization %>
    <%= form.text_field :organization, id: :client_organization %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :client_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :client_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Organization</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.organization %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="clients-show-grid">
	<div>
		<p>
			<strong>Profile:</strong>
			<%= simple_form_for @client, remote: true do |form| %>
				<%= form.input :first_name %>
				<%= form.input :last_name %>
				<%= form.input :organization %>
				<%= form.input :phone %>
				<%= form.input :email %>
				<br/>
				<%= form.submit 'Save' %>
			<% end %>
		</p>
	</div>
	<div>
		<p>
			<strong>Addresses:</strong>
			<%= button_to "Add a new address", new_address_path, params: {addressable_type: 'client', addressable_id: @client.id}, method: :get, id: "add-address-btn", remote: true %>
			<ul id="addresses">
			<% unless @client.addresses.empty? %>
				<% @client.addresses.order(:created_at => :desc).each do |address| %>
					<% if address %>
						<%= render partial: 'addresses/address', locals: { address: address } %>
					<% end %>
				<% end %>
			<% end %>
			</ul>
		</p>
		<div id="address-forms"></div>
	</div>
	<div>
		<p>
			<strong>Funding Information:</strong>

		<div id="funding-info-forms">
		<% if @client.funding_info %>
			<%= render partial: 'funding_infos/funding_info', locals: { funding_info: @client.funding_info } %>
		<% else %>
			<%= button_to "Add funding info", new_funding_info_path, params: { client_id: @client.id }, method: :get, remote: true, id: "add-funding-info-btn" %>
		<% end %>
		</div>

		</p>
	</div>
</div>

app/views/clients/update.js.erb
var notice = document.getElementById('notice')
notice.innerHTML = '<%= @notice %>'
setTimeout(function() {
	notice.innerHTML = ''
}, 2000);