config/routes.rb
Rails.application.routes.draw do
	root to: 'clients#index'
  resources :employee_hours
  resources :clients
  resources :addresses
  resources :expenses
  resources :funding_infos
  resources :jobs
  resources :users
  resources :vendors

  get '/403.html', to: 'application#denied', as: :denied

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :jobs, dependent: :nullify

	def name
		"#{first_name} #{last_name}"
	end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
				@notice = 'Vendor successfully updated'
				format.js   { render 'update.js.erb' }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:first_name, :last_name, :organization, :phone, :email, :blanket_order_number)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= simple_form_for @vendor, remote: true do |form| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :first_name, id: :vendor_first_name %>
  </div>

  <div class="field">
    <%= form.input :last_name, id: :vendor_last_name %>
  </div>

  <div class="field">
    <%= form.input :organization, id: :vendor_organization %>
  </div>

  <div class="field">
    <%= form.input :phone, id: :vendor_phone %>
  </div>

  <div class="field">
    <%= form.input :email, id: :vendor_email %>
  </div>

  <div class="field">
    <%= form.input :blanket_order_number, id: :vendor_blanket_order_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Organization</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Blanket order number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.first_name %></td>
        <td><%= vendor.last_name %></td>
        <td><%= vendor.organization %></td>
        <td><%= vendor.phone %></td>
        <td><%= vendor.email %></td>
        <td><%= vendor.blanket_order_number %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="vendors-show-grid">
	<div>
		<p>
			<strong>Profile:</strong>
			<%= simple_form_for @vendor, remote: true do |form| %>
				<%= form.input :first_name %>
				<%= form.input :last_name %>
				<%= form.input :organization %>
				<%= form.input :phone %>
				<%= form.input :email %>
				<%= form.input :blanket_order_number %>
				<br/>
				<%= form.submit 'Save' %>
			<% end %>
		</p>
	</div>
	<div>
		<p>
			<strong>Addresses:</strong>
			<%= button_to "Add a new address", new_address_path, params: {addressable_type: 'vendor', addressable_id: @vendor.id}, method: :get, id: "add-address-btn", remote: true %>
			<ul id="addresses">
			<% unless @vendor.addresses.empty? %>
				<% @vendor.addresses.order(:created_at => :desc).each do |address| %>
					<% if address %>
						<%= render partial: 'addresses/address', locals: { address: address } %>
					<% end %>
				<% end %>
			<% end %>
			</ul>
		</p>
		<div id="address-forms"></div>
	</div>
</div>

app/views/vendors/update.js.erb
var notice = document.getElementById('notice')
notice.innerHTML = '<%= @notice %>'
setTimeout(function() {
	notice.innerHTML = ''
}, 2000);