config/routes.rb
Rails.application.routes.draw do
	root to: 'clients#index'
  resources :employee_hours
  resources :clients
  resources :addresses
  resources :expenses
  resources :funding_infos
  resources :jobs
  resources :users
  resources :vendors

  get '/403.html', to: 'application#denied', as: :denied

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
		respond_to do |format|
			@address = Address.new
			format.html
			@address = Address.new(addressable_type: params[:addressable_type], addressable_id: params[:addressable_id])
			format.js
		end
  end

  # GET /addresses/1/edit
  def edit
		respond_to do |format|
			format.html
			format.js
		end
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
				format.js
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
				format.js 	{ render 'update.js.erb', notice: 'Address was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
			format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:building, :street, :city, :state, :zip, :country, :addressable_id, :addressable_type)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.erb
<% if address %>
	<li id='address-<%= address.id %>' class='address-partial-grid address'>
		<div id='information'>
			<%= link_to edit_address_path(address), remote: true do %>
				<%= address.building %>
				<%= address.street %>,
				<%= address.city %>,
				<%= address.state %>
				<%= address.zip %>
			<% end %>
		</div>
		<div id='delete'>
			<%= button_to "Delete", address_path(address), method: :delete, remote: true, class: 'delete-button' %>
		</div>
	</li>
<% end %>

app/views/addresses/_form.html.erb
<%= simple_form_for @address, remote: true do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :building, id: :address_building %>
  </div>

    <%= form.input :street, id: :address_street %>
  </div>

  <div class="field">
    <%= form.input :city, id: :address_city %>
  </div>

  <div class="field">
    <%= form.input :state, id: :address_state %>
  </div>

  <div class="field">
    <%= form.input :zip, id: :address_zip %>
  </div>

  <div class="field">
    <%= form.input :addressable_id, as: :hidden, id: :address_addressable_id %>
  </div>

  <div class="field">
    <%= form.input :addressable_type, as: :hidden, id: :address_addressable_type %>
	</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/create.js.erb
document.getElementById('address-forms').innerHTML = ""
var node = document.createElement('li')
node.id = "address-<%= @address.id %>"
node.innerHTML = "<%= j render partial: 'address', locals: { address: @address } %>"
document.getElementById('addresses').prepend(node)
document.getElementById('add-address-btn').style.display = "block"

app/views/addresses/destroy.js.erb
document.getElementById('address-<%= @address.id %>').style.display = "none"

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/edit.js.erb
document.getElementById('address-forms').innerHTML = "<%= j render partial: 'form', locals: { address: @address } %>"
document.getElementById('add-address-btn').style.display = "none"

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Building</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Country</th>
      <th>Addressable</th>
      <th>Addressable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.building %></td>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zip %></td>
        <td><%= address.country %></td>
        <td><%= address.addressable_id %></td>
        <td><%= address.addressable_type %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/new.js.erb
document.getElementById('address-forms').innerHTML = "<%= j render partial: 'form', locals: { address: @address } %>"
document.getElementById('add-address-btn').style.display = "none"

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building:</strong>
  <%= @address.building %>
</p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @address.zip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @address.country %>
</p>

<p>
  <strong>Addressable:</strong>
  <%= @address.addressable_id %>
</p>

<p>
  <strong>Addressable type:</strong>
  <%= @address.addressable_type %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/update.js.erb
document.getElementById('address-<%= @address.id %>').innerHTML = "<%= j render partial: 'address', locals: { address: @address } %>"
document.getElementById('address-forms').innerHTML = ""
document.getElementById('add-address-btn').style.display = "block"